export const PEDOMETER_THRESHOLD = 1.2;
export const PEDOMETER_INTERVAL = 400;
export const PEDOMETER_BUFFER_TIME = 300;

export const TRACKER_MAXIMUM_AGE = 1000;
export const TRACKER_TIMEOUT = 15000;
export const TRACKER_INTERVAL = 5000;
